Repository SJSU-AD/FusionAD, pull requests merged in 2018-10, with the labels that each got.

#77 Finalized Segmentation Edits and Cleanup
  src/modules/localization/CMakeLists.txt
  src/modules/localization/include/localization/kalman_filter/kalman_filter_framework.h
  src/modules/localization/include/localization/segmentation/nanoflann.h
  src/modules/localization/include/localization/segmentation/point_cloud_segmenter.h
  src/modules/localization/include/localization/segmentation/segment_processor.h
  src/modules/localization/include/localization/segmentation/segmenter_node.h
  src/modules/localization/include/localization/segmentation/vec3.h
  src/modules/localization/package.xml
  src/modules/localization/src/kalman_filter/kalman_filter_framework.cpp
  src/modules/localization/src/segmentation/Link to point_cloud_segmenter.cpp
  src/modules/localization/src/segmentation/point_cloud_segmenter.cpp
  src/modules/localization/src/segmentation/segment_processor.cpp
  src/modules/localization/src/segmentation/segmenter_node.cpp
  src/utility/.DS_Store
Labels: bug, enhancement

#83 Control unittest
  ext_package_build.sh
  src/modules/control/CMakeLists.txt
  src/modules/control/include/control/control_node.h
  src/modules/control/include/control/lat_controller.h
  src/modules/control/launch/control.launch
  src/modules/control/package.xml
  src/modules/control/src/control_node.cpp
  src/modules/control/src/lat_controller.cpp
  src/modules/control/test/README.md
  src/modules/control/test/control_test.cpp
  src/modules/control/test/test_data_and_doc/path.h
  src/modules/control/test/test_data_and_doc/path1_spline_from_jojo.csv
  src/modules/control/test/test_data_and_doc/unittest_cases.pdf
  src/utility/swiftnav_ros/CATKIN_IGNORE
  src/utility/swiftnav_ros/CMakeLists.txt
Labels: bug

#82 Iss 81
  src/modules/geodesy/README.md
  src/modules/geodesy/launch/geodesy.launch
  src/modules/geodesy/launch/tf_launch.launch
  src/modules/geodesy/src/path_interpolation.py
  src/modules/geodesy/src/path_interpolator_UTM.py
  src/modules/geodesy/src/tf_master.cpp
Labels: cleanup

#85 Update steering control sign
  arduino/redcar_control/redcar_control.ino
  src/modules/control/launch/control.launch
  src/modules/control/src/ardu_adapter.py
  src/modules/control/src/control_node.cpp
  src/utility/swiftnav_ros/CATKIN_IGNORE
Labels: bug

#88 Control tracking transformation
  src/modules/control/launch/control.launch
  src/modules/control/src/control_node.cpp
  src/utility/swiftnav_ros/CATKIN_IGNORE
Labels: bug, enhancement

#90 IMU Yaw Implementation with consideration of ENU frame TF and Magnetic Declination
  src/modules/control/include/control/control_node.h
  src/modules/control/src/control_node.cpp
  src/modules/interface/msg/Stanley_debug.msg
  src/modules/master_tf/CMakeLists.txt
  src/modules/master_tf/package.xml
Labels: bug, enhancement

#93 Steering Sign Convention Change
  src/modules/control/src/ardu_adapter.py
Labels: cleanup

#96 Imu tf to 90
  src/modules/control/include/control/control_node.h
Labels: bug

#98 ardu_adapter.py restructuring and problem identified
  src/modules/control/src/ardu_adapter.py
Labels: bug

#103 Iss 99
  src/modules/geodesy/launch/geodesy.launch
  src/modules/geodesy/src/path_interpolation.py
  src/modules/geodesy/src/path_interpolator_ENU.py
Labels: cleanup
