Repository SJSU-AD/FusionAD, pull requests merged in 2018-11, with the labels that each got.

#105 Wheel Odometry and Arduino Support Scripts
  arduino/Left_Odom/Left_Odom.ino
  arduino/Right_Odom/Right_Odom.ino
  src/modules/control/launch/control.launch
  src/modules/control/src/ardu_adapter.py
  src/modules/geodesy/geodesy_data/gps_coarse_points/student_union_uTurn.txt
  src/modules/localization/CMakeLists.txt
  src/modules/localization/launch/velocity_estimate.launch
  src/modules/localization/package.xml
  src/modules/localization/src/wheel_odom/Odometry.cpp
  src/modules/localization/src/wheel_odom/Odometry.h
  src/modules/localization/src/wheel_odom/Velocity_Estimation.py
Labels: enhancement

#107 Addition of loam_velodyne and testing covar package for loam_velodyne
  ext_package_build.sh
  src/utility/covar/.gitignore
  src/utility/covar/CMakeLists.txt
  src/utility/covar/README.md
  src/utility/covar/cmake/FindGSL.cmake
  src/utility/covar/include/covar.h
  src/utility/covar/include/covar_lol.h
  src/utility/covar/include/covar_ros.h
  src/utility/covar/package.xml
  src/utility/covar/src/covar_node.cpp
  src/utility/covar/src/example.c
  src/utility/covar/src/file.c
  src/utility/covar/src/file.cpp
  src/utility/covar/srv/gen_both_covar_srv.srv
  src/utility/covar/srv/gen_pose_covar_srv.srv
  src/utility/covar/srv/gen_twist_covar_srv.srv
  src/utility/loam_velodyne/.gitignore
  src/utility/loam_velodyne/CMakeLists.txt
  src/utility/loam_velodyne/LICENSE
  src/utility/loam_velodyne/README.md
  src/utility/loam_velodyne/capture.bmp
  src/utility/loam_velodyne/include/loam_velodyne/Angle.h
  src/utility/loam_velodyne/include/loam_velodyne/BasicLaserMapping.h
  src/utility/loam_velodyne/include/loam_velodyne/BasicLaserOdometry.h
  src/utility/loam_velodyne/include/loam_velodyne/BasicScanRegistration.h
  src/utility/loam_velodyne/include/loam_velodyne/BasicTransformMaintenance.h
  src/utility/loam_velodyne/include/loam_velodyne/CircularBuffer.h
  src/utility/loam_velodyne/include/loam_velodyne/LaserMapping.h
  src/utility/loam_velodyne/include/loam_velodyne/LaserOdometry.h
  src/utility/loam_velodyne/include/loam_velodyne/MultiScanRegistration.h
  src/utility/loam_velodyne/include/loam_velodyne/ScanRegistration.h
  src/utility/loam_velodyne/include/loam_velodyne/TransformMaintenance.h
  src/utility/loam_velodyne/include/loam_velodyne/Twist.h
  src/utility/loam_velodyne/include/loam_velodyne/Vector3.h
  src/utility/loam_velodyne/include/loam_velodyne/common.h
  src/utility/loam_velodyne/include/loam_velodyne/nanoflann.hpp
  src/utility/loam_velodyne/include/loam_velodyne/nanoflann_pcl.h
  src/utility/loam_velodyne/include/loam_velodyne/time_utils.h
  src/utility/loam_velodyne/launch/hector_loam_velodyne.launch
  src/utility/loam_velodyne/launch/loam_velodyne.launch
  src/utility/loam_velodyne/package.xml
  src/utility/loam_velodyne/rviz_cfg/loam_velodyne.rviz
  src/utility/loam_velodyne/src/laser_mapping_node.cpp
  src/utility/loam_velodyne/src/laser_odometry_node.cpp
  src/utility/loam_velodyne/src/lib/BasicLaserMapping.cpp
  src/utility/loam_velodyne/src/lib/BasicLaserOdometry.cpp
  src/utility/loam_velodyne/src/lib/BasicScanRegistration.cpp
  src/utility/loam_velodyne/src/lib/BasicTransformMaintenance.cpp
  src/utility/loam_velodyne/src/lib/CMakeLists.txt
  src/utility/loam_velodyne/src/lib/LaserMapping.cpp
  src/utility/loam_velodyne/src/lib/LaserOdometry.cpp
  src/utility/loam_velodyne/src/lib/MultiScanRegistration.cpp
  src/utility/loam_velodyne/src/lib/ScanRegistration.cpp
  src/utility/loam_velodyne/src/lib/TransformMaintenance.cpp
  src/utility/loam_velodyne/src/lib/math_utils.h
  src/utility/loam_velodyne/src/multi_scan_registration_node.cpp
  src/utility/loam_velodyne/src/transform_maintenance_node.cpp
  src/utility/loam_velodyne/tests/bag_test
  src/utility/loam_velodyne/tests/loam.test.in
Labels: enhancement

#112 Iss 104
  src/modules/control/include/control/control_node.h
  src/modules/control/launch/control.launch
  src/modules/control/src/lat_controller.cpp
  src/modules/control/test/control_test.cpp
  src/utility/covar/CMakeLists.txt
  src/utility/covar/README.md
Labels: bug

#121 Iss 120
  src/modules/localization/include/localization/kalman_filter/kalman_filter_framework.h
  src/modules/localization/src/kalman_filter/kalman_filter_framework.cpp
Labels: cleanup
