Repository SJSU-AD/FusionAD, pull requests merged in 2018-12, with the labels that each got.

#127 Fixing ISS-126
  src/modules/localization/src/wheel_odom/odometry.cpp
Labels: bug

#128 Add odometry message
  src/modules/geodesy/src/gps_pose.py
Labels: enhancement

#137 Iss 123
  src/modules/control/launch/master_control.launch
  src/modules/localization/src/imu_adapter/imu_tf_adapter.cpp
  src/modules/localization/src/imu_adapter/imu_tf_adapter.h
  src/modules/localization/src/wheel_odom/odometry.cpp
  src/modules/localization/src/wheel_odom/odometry.h
Labels: enhancement

#138 Iss 134
  src/modules/geodesy/src/gps_pose.py
Labels: enhancement

#146 Iss 142
  src/modules/geodesy/src/gps_pose.py
  src/modules/localization/src/wheel_odom/odometry.cpp
  src/modules/localization/src/wheel_odom/odometry.h
  src/utility/robot_localization/launch/robot_localization.launch
  src/utility/robot_localization/params/ekf_template.yaml
Labels: bug

#147 Updates to #142
  src/modules/geodesy/src/gps_pose.py
  src/modules/localization/src/wheel_odom/odometry.cpp
  src/modules/localization/src/wheel_odom/odometry.h
  src/utility/robot_localization/params/ekf_template.yaml
Labels: cleanup

#145 Iss 114
  src/modules/geodesy/CMakeLists.txt
  src/modules/geodesy/README.md
  src/modules/geodesy/__init__.py
  src/modules/geodesy/package.xml
  src/modules/geodesy/src/__init__.py
  src/modules/geodesy/src/geodesy.py
  src/modules/geodesy/test/__init__.py
  src/modules/geodesy/test/test_geodesy.py
  src/modules/geodesy/test/test_geodesy.test
  src/modules/geodesy/test/test_gps_parser.py
  src/modules/geodesy/test/test_gps_parser_file1.txt
  src/modules/geodesy/test/test_gps_parser_file2.txt
  src/modules/geodesy/test/test_gps_parser_file3.foo
Labels: enhancement, testing

#150 Iss 133
  src/modules/geodesy/launch/geodesy.launch
  src/modules/geodesy/src/geodesy.py
  src/modules/geodesy/src/geodesy_conversion_ECEF.py
  src/modules/geodesy/src/path_interpolation.py
  src/modules/geodesy/src/path_interpolator_ENU.py
  src/modules/geodesy/test/test_geodesy.py
Labels: enhancement

#154 Iss 153
  src/modules/control/src/control_node.cpp
Labels: enhancement

#152 Iss 141
  src/modules/control/launch/rc.launch
  src/modules/localization/CMakeLists.txt
  src/modules/localization/include/localization/frame_tf_calibrate/frame_calibration.h
  src/modules/localization/include/localization/imu_adapter/imu_tf_adapter.h
  src/modules/localization/include/localization/wheel_odom/odometry.h
  src/modules/localization/launch/state_estimation.launch
  src/modules/localization/launch/velocity_estimate.launch
  src/modules/localization/launch/wheel_odom.launch
  src/modules/localization/src/frame_tf_calibrate/frame_calibration.cpp
  src/modules/localization/src/imu_adapter/imu_tf_adapter.cpp
  src/modules/localization/src/odom_to_chassis_state/odom_to_chassis_state.py
  src/modules/localization/src/wheel_odom/odometry.cpp
  src/modules/master_tf/include/master_tf/master_tf.h
  src/modules/master_tf/src/master_tf.cpp
  src/modules/master_transforms/CMakeLists.txt
  src/modules/master_transforms/include/master_tf.h
  src/modules/master_transforms/package.xml
  src/modules/master_transforms/src/master_tf.cpp
  src/utility/robot_localization/params/ekf_template.yaml
Labels: cleanup, enhancement
