Repository SJSU-AD/FusionAD, pull requests merged in 2018-09, with the labels that each got.

#60 Iss 53
  src/modules/geodesy/geodesy_data/data_validation/back_from_enu.csv
  src/modules/geodesy/geodesy_data/data_validation/back_from_enu_single.csv
  src/modules/geodesy/geodesy_data/data_validation/gps.csv
  src/modules/geodesy/geodesy_data/data_validation/gps_single_point.csv
  src/modules/geodesy/src/geodesy.py
  src/modules/geodesy/src/geodesy_conversion_ECEF.py
  src/modules/geodesy/src/geodesy_conversion_ENU.py
  src/modules/geodesy/src/geodesy_converter_tester.py
Labels: bug

#59 Iss 57
  src/modules/geodesy/CMakeLists.txt
  src/modules/geodesy/include/geodesy/tf_master.h
  src/modules/geodesy/src/tf_master.cpp
  src/modules/interface/CMakeLists.txt
  src/modules/interface/msg/Tf_rotate.msg
Labels: enhancement

#64 Iss 58
  .gitignore
  src/modules/localization/include/segmenter/kalman_filter_framework.h
  src/modules/localization/include/segmenter/point_cloud_segmenter.h
  src/modules/localization/include/segmenter/segment_processor.h
  src/modules/localization/include/segmenter/segmenter_node.h
  src/modules/localization/include/segmenter/vec3.h
  src/modules/localization/src/kalman_filter_framework.cc
  src/modules/localization/src/point_cloud_segmenter.cc
  src/modules/localization/src/segmenter_node.cc
Labels: bug, cleanup

#65 working low level control code
  src/modules/control/src/ardu_adapter.py
Labels: enhancement
