Repository SJSU-AD/FusionAD, pull requests merged in 2019-04, with the labels that each got.

#238 Iss 236
  src/modules/localization/CMakeLists.txt
  src/modules/localization/include/localization/lidar_virtual_box/virtual_box_counter.h
  src/modules/localization/launch/lidar_virtual_box.launch
  src/modules/localization/src/lidar_virtual_box/virtual_box_counter.cpp
  src/modules/localization/src/virtual_box_marker/virtual_box_marker.py
  src/modules/perception/package.xml
Labels: enhancement

#242 Iss 241
  src/modules/control/launch/control.launch
  src/modules/control/src/waypoint_rviz_visualizer.py
Labels: enhancement

#247 Test deployment hotfix
  src/modules/control/launch/can_bus.launch
  src/modules/control/launch/control.launch
  src/modules/control/src/can_control_adapter.py
  src/modules/control/src/can_listener.py
  src/modules/geodesy/geodesy_data/gps_coarse_points/atm_to_eventCenter.txt
  src/modules/localization/launch/state_estimation.launch
  src/modules/localization/src/frame_tf_calibrate/frame_calibration.cpp
  src/utility/control_sil/launch/control_sil_test.launch
Labels: enhancement

#248 Iss 243
  src/modules/master_transforms/include/master_tf.h
  src/modules/master_transforms/src/master_tf.cpp
Labels: enhancement

#249 Iss 246
  src/modules/control/launch/control.launch
  src/modules/localization/launch/lidar_virtual_box.launch
  src/utility/visualization/CMakeLists.txt
  src/utility/visualization/launch/lidar_virtual_box_visualization.launch
  src/utility/visualization/launch/waypoint_visualization.launch
  src/utility/visualization/package.xml
  src/utility/visualization/src/virtual_box_marker.py
  src/utility/visualization/src/waypoint_rviz_visualizer.py
Labels: enhancement

#255 Iss 254
  ext_package_build.sh
  src/modules/control/launch/control.launch
  src/modules/control/launch/master_control.launch
  src/modules/geodesy/geodesy_data/gps_coarse_points/atm_cv2_gym_revised_v2.txt
  src/modules/geodesy/geodesy_data/gps_coarse_points/atm_cv2_gym_revised_v3.txt
  src/modules/geodesy/geodesy_data/gps_coarse_points/atm_cv2_gym_revised_v4.txt
  src/modules/geodesy/geodesy_data/gps_coarse_points/atm_cv2_gym_revised_v5.txt
  src/modules/geodesy/geodesy_data/gps_coarse_points/atm_cv2_gym_revised_v6.txt
  src/modules/geodesy/launch/geodesy.launch
  src/modules/localization/launch/localization.launch
  src/modules/localization/launch/state_estimation.launch
  src/modules/perception/CMakeLists.txt
  src/utility/robot_localization/params/ekf_template.yaml
  src/utility/usb_cam/.gitignore
  src/utility/usb_cam/.travis.yml
  src/utility/usb_cam/AUTHORS.md
  src/utility/usb_cam/CHANGELOG.rst
  src/utility/usb_cam/CMakeLists.txt
  src/utility/usb_cam/LICENSE
  src/utility/usb_cam/README.md
  src/utility/usb_cam/include/usb_cam/usb_cam.h
  src/utility/usb_cam/launch/usb_cam_test_osv.launch
  src/utility/usb_cam/mainpage.dox
  src/utility/usb_cam/nodes/usb_cam_node.cpp
  src/utility/usb_cam/package.xml
  src/utility/usb_cam/src/LICENSE
  src/utility/usb_cam/src/usb_cam.cpp
Labels: cleanup

#257 Iss 256
  src/modules/interface/CMakeLists.txt
  src/modules/interface/msg/Cluster_bound.msg
  src/modules/interface/msg/Cluster_bound_list.msg
  src/modules/localization/CMakeLists.txt
  src/modules/localization/include/localization/lidar_virtual_box/virtual_box_counter.h
  src/modules/localization/launch/cluster_tracker.launch
  src/modules/localization/launch/lidar_virtual_box.launch
  src/modules/localization/package.xml
  src/modules/localization/src/lidar_virtual_box/cluster_tracker.py
  src/modules/localization/src/lidar_virtual_box/virtual_box_counter.cpp
  src/utility/visualization/launch/cluster_bound_visualization.launch
  src/utility/visualization/src/cluster_bound_visualizer.py
  src/utility/visualization/src/virtual_box_marker.py
Labels: enhancement, experiment
