Repository SJSU-AD/FusionAD, pull requests merged in 2019-02, with the labels that each got.

#211 Iss 205
  src/modules/localization/include/localization/frame_tf_calibrate/frame_calibration.h
  src/modules/localization/include/localization/wheel_odom/odometry.h
  src/modules/localization/launch/state_estimation.launch
  src/modules/localization/src/frame_tf_calibrate/frame_calibration.cpp
  src/modules/localization/src/wheel_odom/odometry.cpp
  src/modules/master_transforms/include/master_tf.h
  src/modules/master_transforms/src/master_tf.cpp
  src/utility/robot_localization/launch/robot_localization.launch
  src/utility/robot_localization/launch/temporary_robot_localization_test.launch
  src/utility/robot_localization/params/ekf_template.yaml
  src/utility/robot_localization/params/ukf_template.yaml
Labels: experiment

#213 Iss 212
  src/modules/geodesy/geodesy_data/gps_coarse_points/student_union_straight_long.txt
  src/modules/geodesy/launch/geodesy.launch
Labels: enhancement

#215 Iss 214
  src/modules/localization/include/localization/frame_tf_calibrate/frame_calibration.h
  src/modules/localization/launch/state_estimation.launch
  src/modules/localization/src/ekf_orientation_to_imu/ekf_orientation_to_imu.py
  src/modules/localization/src/frame_tf_calibrate/frame_calibration.cpp
  src/modules/localization/src/odom_to_chassis_state/odom_to_chassis_state.py
  src/modules/master_transforms/include/master_tf.h
  src/modules/master_transforms/src/master_tf.cpp
  src/utility/robot_localization/params/ekf_template.yaml
Labels: enhancement, experiment

#225 Iss 216
  src/modules/geodesy/geodesy_data/data_validation/enuToLatLon_gpsData_fromBag.txt
  src/modules/geodesy/geodesy_data/data_validation/enuToLatLon_path_fromBag.txt
  src/modules/geodesy/launch/geodesy.launch
  src/modules/geodesy/src/geodesy_conversion_ENU.py
  src/modules/geodesy/src/gps_pose.py
  src/modules/geodesy/src/path_interpolation.py
  src/modules/geodesy/src/path_interpolator_ENU.py
  src/modules/geodesy/src/validate_enu_to_latlon.py
Labels: enhancement

#226 Add smoother path
  src/modules/geodesy/geodesy_data/gps_coarse_points/campus_uPath_smooth.txt
  src/modules/geodesy/launch/geodesy.launch
  src/modules/geodesy/src/geodesy_conversion_ENU.py
  src/modules/geodesy/src/gps_pose.py
  src/modules/geodesy/src/path_interpolation.py
Labels: enhancement

#231 Iss 228
  src/modules/localization/include/localization/frame_tf_calibrate/frame_calibration.h
  src/modules/localization/launch/state_estimation.launch
  src/modules/localization/src/frame_tf_calibrate/frame_calibration.cpp
Labels: enhancement, experiment

#229 Iss 224
  src/modules/geodesy/geodesy_data/gps_coarse_points/fullCirclePath_ENU_sample.csv
  src/modules/geodesy/launch/geodesy.launch
  src/modules/geodesy/src/gps_parser.py
  src/modules/geodesy/src/gps_pose.py
  src/modules/geodesy/src/path_interpolation.py
  src/modules/geodesy/src/path_interpolator_ENU.py
Labels: enhancement, experiment
