Repository SJSU-AD/FusionAD, pull requests merged in 2019-01, with the labels that each got.

#161 Iss 160
  src/modules/localization/src/odom_to_chassis_state/odom_to_chassis_state.py
Labels: cleanup

#162 Iss 157
  src/modules/control/include/control/control_node.h
  src/modules/control/src/control_node.cpp
Labels: cleanup, enhancement

#163 Remove tf_master
  src/modules/geodesy/CMakeLists.txt
  src/modules/geodesy/include/geodesy/tf_master.h
  src/modules/geodesy/launch/tf_launch.launch
  src/modules/geodesy/src/tf_master.cpp
Labels: cleanup

#159 Iss 113
  src/modules/control/CMakeLists.txt
  src/modules/control/include/control/control_node.h
  src/modules/control/include/control/lib_high_level_control.h
  src/modules/control/package.xml
  src/modules/control/src/control_node.cpp
  src/modules/control/src/lib_high_level_control.cpp
  src/modules/control/test/README.md
  src/modules/control/test/control_path_test.cpp
  src/modules/control/test/lateral_control_test.cpp
  src/modules/control/test/test_data_and_doc/transform_test.m
  src/modules/control/test/test_data_and_doc/unittest_cases_wp_selector.pdf
Labels: enhancement

#173 Iss 166
  src/modules/localization/launch/wheel_odom.launch
  src/modules/localization/src/frame_tf_calibrate/frame_calibration.cpp
  src/utility/robot_localization/params/ekf_template.yaml
Labels: cleanup

#175 Change pose subscription topic
  src/modules/geodesy/src/gps_pose.py
Labels: Experiment

#177 Remove publish to /localization/state
  src/modules/geodesy/src/gps_pose.py
Labels: cleanup

#180 Iss 179
  src/modules/localization/src/wheel_odom/odometry.cpp
  src/utility/robot_localization/params/ekf_template.yaml
Labels: cleanup

#187 Iss 185
  src/modules/control/launch/pure_high_lvl_control.launch
  src/modules/control/src/control_node.cpp
  src/modules/control/src/lat_controller.cpp
  src/modules/control/test/lateral_control_test.cpp
  src/modules/interface/msg/Stanley_debug.msg
  src/utility/swiftnav_ros/CATKIN_IGNORE
Labels: bug, cleanup

#193 Iss 178
  src/modules/geodesy/launch/geodesy.launch
  src/modules/geodesy/src/gps_pose.py
  src/modules/geodesy/src/path_interpolation.py
  src/modules/geodesy/src/path_interpolator_ENU.py
  src/utility/usb_cam/launch/usb_cam-test.launch
Labels: cleanup, enhancement

#197 Iss 196
  src/modules/perception/config/velodyne_cam.rviz
Labels: enhancement

#201 Merging changes in readme and the install script into test_deployment
  README.md
  ext_package_build.sh
Labels: cleanup, enhancement
